version: '3.9'

services:
    mysql:
        image: mysql:8.0
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: wordpress
            MYSQL_USER: user
            MYSQL_PASSWORD: password

    platform:
        depends_on:
            - mysql
        image: wordpress:6.4-apache
        ports:
            - '80:80'
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: user
            WORDPRESS_DB_PASSWORD: password
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html/wp-content/plugins/easyappointments

